"use client";

import { useEffect, useState } from "react";
import { TbBell, TbTrash, TbInfoCircle, TbCheck, TbAlertTriangle, TbX, TbClock } from "react-icons/tb";
import {
    CiBellOn as Bell,
} from "react-icons/ci";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/lightswind/popover";
import { useNotificationStore } from "@/stores/notificationStore";
import { formatDistanceToNow } from "date-fns";
import { createNotification } from "@/lib/api/notifications";
import { toast } from "sonner"; // Use toast to sync

export function NotificationCenter() {
    const [open, setOpen] = useState(false);
    const {
        notifications,
        unreadCount,
        isLoading,
        fetchNotifications,
        markAsRead,
        markAllAsRead,
        deleteNotification,
        addNotification // Exposed for manual test creation
    } = useNotificationStore();

    // Initial fetch and faster polling (15s)
    useEffect(() => {
        fetchNotifications(false);
        const interval = setInterval(() => fetchNotifications(false), 15000);
        return () => clearInterval(interval);
    }, [fetchNotifications]);

    // State to track last seen notification ID for toasts
    const [lastId, setLastId] = useState<number | null>(null);

    // Toast logic: Watch for new notifications
    useEffect(() => {
        if (!isLoading && notifications.length > 0) {
            const newestId = notifications[0].id;

            // First load or no previous tracking: just set ID
            if (lastId === null) {
                setLastId(newestId);
                return;
            }

            // New notifications found
            if (newestId > lastId) {
                // Find all new ones
                const newItems = notifications.filter(n => n.id > lastId);

                newItems.forEach(n => {
                    // Trigger toast based on type
                    const toastFn = n.type === 'error' ? toast.error :
                        n.type === 'success' ? toast.success :
                            n.type === 'warning' ? toast.warning : toast.message;

                    toastFn(n.title, {
                        description: n.message,
                        cancel: {
                            label: 'View',
                            onClick: () => {
                                // Logic to view? maybe expand center?
                                // For now just nice to have.
                            }
                        }
                    });
                });

                setLastId(newestId);
            }
        }
    }, [notifications, lastId, isLoading]);

    const [lastChecked, setLastChecked] = useState(new Date());

    // Update last checked when opening
    const onOpenChange = (isOpen: boolean) => {
        setOpen(isOpen);
        if (isOpen) setLastChecked(new Date());
    };

    // Helper for the "Test Notification" button
    const handleCreateTestNotification = async () => {
        try {
            const newNotif = await createNotification("Test Notification", "This is a test notification generated by the user.");
            // Store's addNotification handles optimistic update if we wanted,
            // but here we just re-fetch or let polling catch it.
            // Better: use the store's addNotification to show it instantly if specific format matches
            addNotification(newNotif);
        } catch (e) {
            console.error(e);
        }
    };

    return (
        <Popover open={open} onOpenChange={onOpenChange}>
            <PopoverTrigger asChild>
                <button className="relative rounded-full p-2 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring icon-xl">
                    <Bell className="h-5 w-5" />
                    {unreadCount > 0 && (
                        <div className="absolute right-1.5 top-1.5 flex h-4 w-4 items-center justify-center rounded-full bg-red-500 text-[10px] font-bold text-center text-white ring-2 ring-background animate-bounce">
                            {unreadCount > 9 ? "9+" : unreadCount}
                        </div>
                    )}
                    <span className="sr-only">Notifications</span>
                </button>
            </PopoverTrigger>
            <PopoverContent className="w-[380px] p-0 overflow-hidden rounded-2xl border border-border/50 bg-popover/95 backdrop-blur-xl shadow-2xl" align="end">
                {/* Header */}
                <div className="flex items-center justify-between border-b border-border/40 bg-muted/20 px-4 py-3">
                    <div className="space-y-0.5">
                        <h4 className="font-semibold text-sm">Notifications</h4>
                        {unreadCount > 0 ? (
                            <p className="text-[10px] text-muted-foreground">{unreadCount} unread</p>
                        ) : (
                            <p className="text-[10px] text-muted-foreground">You're all caught up</p>
                        )}
                    </div>
                    <div className="flex items-center gap-1">
                        <button
                            onClick={handleCreateTestNotification}
                            className="rounded-full p-1.5 text-muted-foreground hover:bg-muted hover:text-foreground transition-colors"
                            title="Test Notification"
                        >
                            <span className="text-xs font-bold">+</span>
                        </button>
                        {unreadCount > 0 && (
                            <button
                                onClick={() => markAllAsRead()}
                                className="flex items-center gap-1 rounded-full px-2 py-1 text-xs font-medium text-primary hover:bg-primary/10 transition-colors"
                                title="Mark all as read"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>
                                Mark all
                            </button>
                        )}
                    </div>
                </div>

                {/* Content */}
                <div className="max-h-[60vh] overflow-y-auto">
                    {isLoading && notifications.length === 0 ? (
                        <div className="flex h-40 items-center justify-center text-sm text-muted-foreground">
                            <svg className="h-5 w-5 animate-spin mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                            </svg>
                            Loading...
                        </div>
                    ) : notifications.length === 0 ? (
                        <div className="flex flex-col items-center justify-center py-12 px-4 text-center">
                            <div className="mb-4 rounded-full bg-primary/10 p-3 ring-1 ring-primary/50">
                                <TbBell className="h-8 w-8 text-primary/80" />
                            </div>
                            <h5 className="mb-1 text-sm font-medium text-foreground/90">No notifications yet</h5>
                            <p className="text-xs text-muted-foreground max-w-[200px]">
                                We'll notify you when there's an update on your tasks or activity.
                            </p>
                        </div>
                    ) : (
                        <div className="divide-y divide-border/40">
                            {notifications.map((notification) => {
                                // Determine Icon and Color
                                let Icon = TbInfoCircle;
                                let colorClass = "text-blue-500 bg-blue-500/10";

                                // Enhanced Icon Logic
                                if (notification.category === "reminder") {
                                    Icon = TbClock;
                                    colorClass = "text-purple-500 bg-purple-500/10";
                                } else {
                                    switch (notification.type) {
                                        case "success":
                                            Icon = TbCheck;
                                            colorClass = "text-green-500 bg-green-500/10";
                                            break;
                                        case "warning":
                                            Icon = TbAlertTriangle;
                                            colorClass = "text-yellow-500 bg-yellow-500/10";
                                            break;
                                        case "error":
                                            Icon = TbX;
                                            colorClass = "text-red-500 bg-red-500/10";
                                            break;
                                    }
                                }

                                const isOverdue = notification.type === 'error' && notification.category === 'task';

                                return (
                                    <div
                                        key={notification.id}
                                        className={`group relative flex items-start gap-3 p-4 transition-all hover:bg-muted/50 ${!notification.is_read ? "bg-muted/30" : ""}`}
                                    >
                                        {!notification.is_read && (
                                            <div className={`absolute left-0 top-4 h-2 w-2 rounded-full ${colorClass.split(" ")[0]}`} />
                                        )}

                                        <div className={`mt-0.5 rounded-full p-1.5 ${colorClass}`}>
                                            <Icon className="h-4 w-4" />
                                        </div>

                                        <div className="flex-1 space-y-1 min-w-0">
                                            <div className="flex items-start justify-between gap-2">
                                                <p className={`text-sm font-medium leading-none ${!notification.is_read ? "text-foreground" : "text-muted-foreground"}`}>
                                                    {notification.title}
                                                </p>
                                                <span className="text-[10px] text-muted-foreground shrink-0 tabular-nums">
                                                    {formatDistanceToNow(new Date(notification.created_at + (notification.created_at.endsWith("Z") ? "" : "Z")), { addSuffix: true })}
                                                </span>
                                            </div>
                                            <p className="text-xs text-muted-foreground line-clamp-2">
                                                {notification.message}
                                            </p>
                                            {!notification.is_read && (
                                                <button
                                                    onClick={(e) => {
                                                        e.stopPropagation();
                                                        markAsRead(notification.id);
                                                    }}
                                                    className="text-[10px] font-medium text-primary hover:underline pt-1"
                                                >
                                                    Mark as read
                                                </button>
                                            )}
                                        </div>
                                        {!isOverdue && (
                                            <button
                                                onClick={(e) => {
                                                    e.stopPropagation();
                                                    deleteNotification(notification.id);
                                                }}
                                                className="ml-auto rounded-full p-1 text-muted-foreground opacity-0 hover:bg-background hover:text-destructive group-hover:opacity-100 transition-opacity"
                                                title="Delete"
                                            >
                                                <TbTrash className="h-4 w-4" />
                                            </button>
                                        )}
                                    </div>
                                );
                            })}
                        </div>
                    )}
                </div>

                {/* Footer */}
                <div className="border-t border-border/40 bg-muted/10 px-4 py-2 text-center">
                    <p className="text-[10px] text-muted-foreground/60">
                        Last checked: {lastChecked.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: true })}
                    </p>
                </div>
            </PopoverContent>
        </Popover>
    );
}
