apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-backend.fullname" . }}-config
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
data:
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}
