apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-backend.fullname" . }}-secret
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.betterAuthSecret | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | quote }}
