"""add_cascade_delete_fix_2

Revision ID: 2c35cbee8374
Revises: 9de96fabb6f2
Create Date: 2026-01-18 20:23:41.925791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c35cbee8374'
down_revision: Union[str, Sequence[str], None] = '9de96fabb6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('account_userId_idx'), table_name='account')
    # op.drop_table('account')
    # op.drop_table('user')
    # op.drop_index(op.f('verification_identifier_idx'), table_name='verification')
    # op.drop_table('verification')
    # op.drop_index(op.f('session_userId_idx'), table_name='session')
    # op.drop_table('session')
    op.drop_constraint(op.f('chatkit_items_thread_id_fkey'), 'chatkit_items', type_='foreignkey')
    op.create_foreign_key(None, 'chatkit_items', 'chatkit_threads', ['thread_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatkit_items', type_='foreignkey')
    op.create_foreign_key(op.f('chatkit_items_thread_id_fkey'), 'chatkit_items', 'chatkit_threads', ['thread_id'], ['id'])
    # op.create_table('session', ...) - Removed to protect auth tables
    # op.create_table('verification', ...) - Removed to protect auth tables
    # op.create_table('user', ...) - Removed to protect auth tables
    # op.create_table('account', ...) - Removed to protect auth tables
    # ### end Alembic commands ###
