"""switch reminder offset to remind_at

Revision ID: 6e8329ff691d
Revises: e293347439ce
Create Date: 2026-02-04 21:39:15.037029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e8329ff691d'
down_revision: Union[str, Sequence[str], None] = 'e293347439ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatkit_items', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('chatkit_threads', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('reminder', sa.Column('remind_at', sa.DateTime(), nullable=False))
    op.drop_column('reminder', 'offset_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('offset_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('reminder', 'remind_at')
    op.alter_column('chatkit_threads', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('chatkit_items', 'content',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
