"""add_chatkit_tables

Revision ID: 9de96fabb6f2
Revises: db15fc05a45f
Create Date: 2026-01-18 20:15:48.487830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9de96fabb6f2'
down_revision: Union[str, Sequence[str], None] = 'db15fc05a45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatkit_threads',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatkit_threads_user_id'), 'chatkit_threads', ['user_id'], unique=False)
    op.create_table('chatkit_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chatkit_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatkit_items_thread_id'), 'chatkit_items', ['thread_id'], unique=False)
    # op.drop_table('user') - Removed to protect auth tables
    # op.drop_index(op.f('verification_identifier_idx'), table_name='verification')
    # op.drop_table('verification')
    # op.drop_index(op.f('session_userId_idx'), table_name='session')
    # op.drop_table('session')
    # op.drop_index(op.f('account_userId_idx'), table_name='account')
    # op.drop_table('account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('account', ...) - Removed to protect auth tables
    # op.create_table('session', ...) - Removed to protect auth tables
    # op.create_table('verification', ...) - Removed to protect auth tables
    # op.create_table('user', ...) - Removed to protect auth tables
    op.drop_index(op.f('ix_chatkit_items_thread_id'), table_name='chatkit_items')
    op.drop_table('chatkit_items')
    op.drop_index(op.f('ix_chatkit_threads_user_id'), table_name='chatkit_threads')
    op.drop_table('chatkit_threads')
    # ### end Alembic commands ###
