"""Add overdue_notified_at to task

Revision ID: aeeb0150db27
Revises: 6e8329ff691d
Create Date: 2026-02-05 14:01:30.788975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aeeb0150db27'
down_revision: Union[str, Sequence[str], None] = '6e8329ff691d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('notification', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('notification', sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('task', sa.Column('overdue_notified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'overdue_notified_at')
    op.drop_column('notification', 'link')
    op.drop_column('notification', 'category')
    op.drop_column('notification', 'type')
    # ### end Alembic commands ###
