"""Add status, priority, and due_date fields

Revision ID: db15fc05a45f
Revises: 5062915dbd00
Create Date: 2026-01-13 20:15:59.787735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db15fc05a45f'
down_revision: Union[str, Sequence[str], None] = '5062915dbd00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing drop_table commands for Better Auth tables
    op.add_column('task', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), server_default="todo", nullable=False))
    op.add_column('task', sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=20), server_default="medium", nullable=False))
    op.add_column('task', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_task_due_date'), 'task', ['due_date'], unique=False)
    op.create_index(op.f('ix_task_priority'), 'task', ['priority'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_priority'), table_name='task')
    op.drop_index(op.f('ix_task_due_date'), table_name='task')
    op.drop_column('task', 'due_date')
    op.drop_column('task', 'priority')
    op.drop_column('task', 'status')
    op.drop_column('task', 'status')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
